// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1735.RobotMockup;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Victor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController motorSubMotor;
    public static Solenoid lightSubLightRelay;
    public static DigitalInput lightSubLightSwitch;
    public static SpeedController drivetrainSpeedControllerL;
    public static SpeedController drivetrainSpeedControllerR;
    public static RobotDrive drivetrainRobotDrive21;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        motorSubMotor = new Victor(2);
        LiveWindow.addActuator("MotorSub", "Motor", (Victor) motorSubMotor);
        
        lightSubLightRelay = new Solenoid(0, 0);
        LiveWindow.addActuator("LightSub", "LightRelay", lightSubLightRelay);
        
        lightSubLightSwitch = new DigitalInput(0);
        LiveWindow.addSensor("LightSub", "LightSwitch", lightSubLightSwitch);
        
        drivetrainSpeedControllerL = new Victor(0);
        LiveWindow.addActuator("Drivetrain", "Speed Controller L", (Victor) drivetrainSpeedControllerL);
        
        drivetrainSpeedControllerR = new Victor(1);
        LiveWindow.addActuator("Drivetrain", "Speed Controller R", (Victor) drivetrainSpeedControllerR);
        
        drivetrainRobotDrive21 = new RobotDrive(drivetrainSpeedControllerL, drivetrainSpeedControllerR);
        
        drivetrainRobotDrive21.setSafetyEnabled(true);
        drivetrainRobotDrive21.setExpiration(0.1);
        drivetrainRobotDrive21.setSensitivity(0.5);
        drivetrainRobotDrive21.setMaxOutput(1.0);
        drivetrainRobotDrive21.setInvertedMotor(RobotDrive.MotorType.kRearLeft, true);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
