// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1735.RobotMockup.subsystems;

import org.usfirst.frc1735.RobotMockup.RobotMap;
import org.usfirst.frc1735.RobotMockup.commands.*;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Solenoid;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class LightSub extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final Solenoid lightRelay = RobotMap.lightSubLightRelay;
    private final DigitalInput lightSwitch = RobotMap.lightSubLightSwitch;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new EnableLight());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public void setLightOn() {
    	lightRelay.set(true);
    }
    public void setLightOff() {
    	lightRelay.set(false);
    }

	public boolean isSwitchPressed() {
		// Switch is wired so that pressed = 0/false.
		// (That way, if it becomes disconnected, the value becomes 1 and we don't sense the switch as active)
		// (The RoboRio is wired internally to make inputs == 1 if not connected)
		// We want to return true if pressed... Therefore, we return the opposite of what the switch returned.
		return !lightSwitch.get();
	}
}

